/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infoprojektbildmanipulation;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;

/**
 *
 * @author Nicolai Müller
 */
public class Hauptfenster extends javax.swing.JFrame {

    BufferedImage bi=null;
    BufferedImage bildoriginal=null;
    Effects picture = null;
    /**
     * Creates new form Hauptfenster
     */
    public Hauptfenster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jPanel1kl = new javax.swing.JPanel(){
            public void paintComponent(Graphics f){
                super.paintComponent(f);
                zeichneBildKlein(f);
            }
        };
        laden = new javax.swing.JButton();
        speichern = new javax.swing.JButton();
        jPanel2gr = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                super.paintComponent(g);
                zeichneBildGross(g);
            }
        };
        waehlen = new javax.swing.JButton();
        Verwirbeln = new javax.swing.JButton();
        Wellen = new javax.swing.JButton();
        Einrollen = new javax.swing.JButton();
        Leinwand = new javax.swing.JButton();
        Ölbild = new javax.swing.JButton();
        Kaffee = new javax.swing.JButton();
        Puzzle = new javax.swing.JButton();
        Comic = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1klLayout = new javax.swing.GroupLayout(jPanel1kl);
        jPanel1kl.setLayout(jPanel1klLayout);
        jPanel1klLayout.setHorizontalGroup(
            jPanel1klLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel1klLayout.setVerticalGroup(
            jPanel1klLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        laden.setText("laden");
        laden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ladenActionPerformed(evt);
            }
        });

        speichern.setText("speichern");
        speichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speichernActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2grLayout = new javax.swing.GroupLayout(jPanel2gr);
        jPanel2gr.setLayout(jPanel2grLayout);
        jPanel2grLayout.setHorizontalGroup(
            jPanel2grLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2grLayout.setVerticalGroup(
            jPanel2grLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        waehlen.setText("wählen");
        waehlen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waehlenActionPerformed(evt);
            }
        });

        Verwirbeln.setText("Verwirbeln");
        Verwirbeln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerwirbelnActionPerformed(evt);
            }
        });

        Wellen.setText("Wellen");
        Wellen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WellenActionPerformed(evt);
            }
        });

        Einrollen.setText("Einrollen");
        Einrollen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EinrollenActionPerformed(evt);
            }
        });

        Leinwand.setText("Leinwand");
        Leinwand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeinwandActionPerformed(evt);
            }
        });

        Ölbild.setText("Ölbild");
        Ölbild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÖlbildActionPerformed(evt);
            }
        });

        Kaffee.setText("Kaffee");
        Kaffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaffeeActionPerformed(evt);
            }
        });

        Puzzle.setText("Puzzle");
        Puzzle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuzzleActionPerformed(evt);
            }
        });

        Comic.setText("Comic");
        Comic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2gr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(waehlen, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(laden, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(speichern))
                            .addComponent(jTextField1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1kl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Verwirbeln, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Wellen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Einrollen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Leinwand, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ölbild, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Kaffee, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Puzzle, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(Comic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(speichern)
                                .addComponent(laden)
                                .addComponent(waehlen)))
                        .addComponent(jPanel1kl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Verwirbeln)
                            .addComponent(Einrollen)
                            .addComponent(Ölbild)
                            .addComponent(Puzzle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Wellen)
                            .addComponent(Leinwand)
                            .addComponent(Kaffee)
                            .addComponent(Comic))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2gr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Auswählen des Bildes
    private void waehlenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waehlenActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File("/"));
        int zahl = fc.showOpenDialog(this);
        File f=fc.getSelectedFile();
        jTextField1.setText(f.getAbsolutePath());
    }//GEN-LAST:event_waehlenActionPerformed

    // Laden des Bildes
    private void ladenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ladenActionPerformed
        String pfad=jTextField1.getText();
        if (pfad!=null){
            try {
                bi=ImageIO.read(new File(pfad));
                picture = new Effects(bi);
                bildoriginal=bi;
                
                Graphics g=jPanel1kl.getGraphics();
                int b=jPanel1kl.getWidth();
                int hneu1=bildoriginal.getHeight()*b/bildoriginal.getWidth();
                 g.drawImage(bildoriginal, 0, 0, b, hneu1, this);
                       
                jPanel2gr.repaint();
            } catch (IOException ex) {
                System.out.println("Beim Laden der Datei ist ein Fehler aufgetreten!");
            }
        }
    }//GEN-LAST:event_ladenActionPerformed

    private void VerwirbelnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerwirbelnActionPerformed
        if(picture != null){
            picture.Verwirbeln(200,200,1,10); //Muss geändert werden
        }
    }//GEN-LAST:event_VerwirbelnActionPerformed

    private void WellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WellenActionPerformed
        if(picture != null){
            picture.Wellen();
        }
    }//GEN-LAST:event_WellenActionPerformed

    private void EinrollenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EinrollenActionPerformed
        if(picture != null){
            picture.Einrollen();
        }
    }//GEN-LAST:event_EinrollenActionPerformed

    private void LeinwandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeinwandActionPerformed
        // Hier bitte den Quellcode für die Leinwand einfügen.
    }//GEN-LAST:event_LeinwandActionPerformed

    private void ÖlbildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÖlbildActionPerformed
        // Hier bitte den Quellcode zum Ölbild einfügen.
    }//GEN-LAST:event_ÖlbildActionPerformed

    private void KaffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaffeeActionPerformed
        // Hier den Quellcode für den Kaffeefleck einfügen
    }//GEN-LAST:event_KaffeeActionPerformed

    private void PuzzleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuzzleActionPerformed
        // Hier bitte den Quellcode für das Puzzle einfügen.
    }//GEN-LAST:event_PuzzleActionPerformed

    private void ComicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComicActionPerformed
        // Hier bitte den Quellcode für den Comiceffekt einfügen.
    }//GEN-LAST:event_ComicActionPerformed

    private void speichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speichernActionPerformed
         
        final JFileChooser fc = new JFileChooser();

        fc.setCurrentDirectory(new File("/"));
        int zahl = fc.showSaveDialog(this);
        File f=fc.getSelectedFile();
        System.out.println("Speichern als "+f.getAbsolutePath());
        
        try {
            ImageIO.write(bi, "png", f);
        } catch (IOException ex) {
            System.out.println("Beim Speichern der Datei ist ein Problem aufgetreten!");
        }
    }//GEN-LAST:event_speichernActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hauptfenster().setVisible(true);
            }
        });
    }

    public void zeichneBildKlein(Graphics h){
        if (bi!=null){

            int w=jPanel1kl.getWidth();
            int hneu=bildoriginal.getHeight()*w/bildoriginal.getWidth();
            
            h.drawImage(bildoriginal, 0, 0, w, hneu, this);
        } else {
            h.setColor(new Color(255,255,255));
            h.fillRect(0, 0, jPanel1kl.getWidth(), jPanel1kl.getHeight());
        }
    }
    
    public void zeichneBildGross(Graphics g){
        if (bi!=null){

            int w=jPanel2gr.getWidth();
            int hneu=bi.getHeight()*w/bi.getWidth();
            
            g.drawImage(bi,0 , 0, w,hneu,this);
        } else {
            g.setColor(new Color(255,255,255));
            g.fillRect(0, 0, jPanel2gr.getWidth(), jPanel2gr.getHeight());
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comic;
    private javax.swing.JButton Einrollen;
    private javax.swing.JButton Kaffee;
    private javax.swing.JButton Leinwand;
    private javax.swing.JButton Puzzle;
    private javax.swing.JButton Verwirbeln;
    private javax.swing.JButton Wellen;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1kl;
    private javax.swing.JPanel jPanel2gr;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton laden;
    private javax.swing.JButton speichern;
    private javax.swing.JButton waehlen;
    private javax.swing.JButton Ölbild;
    // End of variables declaration//GEN-END:variables
}
